---
- name: Install Docker on Test Server
  hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common]
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io]
        update_cache: yes

    - name: Ensure docker is running
      service:
        name: docker
        state: started
        enabled: yes
